name: Build MQTT Operations Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile
    - name: Make installer
      uses: joncloud/makensis-action@v3.6
      with:
        # Path to the .nsi script file
        script-file: installer.nsi
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: MQTTOperationsService-Installer
        path: MQTTOperationsService-Installer.exe
        
        
      
